[tool.poetry]
name = "tic-tac-toe-bot"
version = "0.1.0"
description = ""
authors = ["Maxim Shelestov <shelestov.maxim@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.*"
python-telegram-bot = "^20.7"
